# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
#        metadata_cache_driver: apcu
#        query_cache_driver: apcu
#        result_cache_driver: apcu
#        second_level_cache:
#            region_cache_driver:
#                type:           apcu
#            enabled:              true
#            log_enabled:          true
#            regions:
#                my_region:
#                    cache_driver:  apcu
#                    lifetime:   3600

#simple_things_entity_audit:
#    audited_entities:
#        - AppBundle\Entity\Post
#        - AppBundle\Entity\Comment
#    global_ignore_properties:
#        - createdAt

#doctrine_migrations:
#    dir_name: "%kernel.root_dir%/DoctrineMigrations"
#    namespace: CIANDT\Migrations
#    table_name: migration_versions
#    name: C&T Migrations
