# src/AppBundle\Entity\Product
AppBundle\Entity\Product:
    product_1:
        name: <text(100)>
        price:  <numberBetween(10, 999)>
        category: '@marmita_1'
        dailyMenus: ['@cardapio1']
        updatedAt: <datetimeBetween('-5 days', 'now')>
        createdAt: <datetimeBetween('-5 days', 'now')>

    product_2:
        name: <text(100)>
        price:  <numberBetween(10, 999)>
        category: '@marmita_2'
        dailyMenus: ['@cardapio2','@cardapio1']
        updatedAt: <datetimeBetween('-5 days', 'now')>
        createdAt: <datetimeBetween('-5 days', 'now')>

    product_{3..20}:
        name: <text(100)>
        price:  <numberBetween(10, 999)>
        category: '@marmita_3'
        dailyMenus: ['@cardapio3', '@cardapio2']
        updatedAt: <datetimeBetween('-5 days', 'now')>
        createdAt: <datetimeBetween('-5 days', 'now')>

    product_{21..40}:
        name: <text(100)>
        price:  <numberBetween(10, 999)>
        category: '@marmita_drinks'
        dailyMenus: ['@cardapio4','@cardapio3']
        updatedAt: <datetimeBetween('-5 days', 'now')>
        createdAt: <datetimeBetween('-5 days', 'now')>

    product_{41..60}:
        name: <text(100)>
        price:  <numberBetween(10, 999)>
        category: '@marmita_accompaniment'
        dailyMenus: ['@cardapio5', '@cardapio6']
        updatedAt: <datetimeBetween('-5 days', 'now')>
        createdAt: <datetimeBetween('-5 days', 'now')>
