phpcs:
    standard: PSR2
    # number of allowed errors is compared with warnings+errors, or just errors from checkstyle.xml
    ignoreWarnings: true
    # https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting
    reports:
        cli:
            - full
        file:
            # checkstyle is always included and overriden
            checkstyle: checkstyle.xml
            # you can include custom reports (https://github.com/wikidi/codesniffer/blob/master/reports/wikidi/Summary.php#L39)
            # ./vendor/owner/package/src/MySummaryReport.php: phpcs-summary.html

php-cs-fixer:
    # http://cs.sensiolabs.org/#usage
    rules: '@PSR2'
    allowRiskyRules: false
    # by default the tool is runned in dry-run mode (no fixers are applied)
    isDryRun: true
    # alternatively you can define path to your .phpcs_file (rules/allowRiskyRules config is ignored)
    config: null

phpmd:
    standard: phpmd.xml

phpcpd:
    minLines: 5
    minTokens: 70

phpmetrics:

phpstan:
    level: 1
    # https://github.com/phpstan/phpstan#configuration
    # standard: tests/.travis/phpstan.neon
phploc:
    progress: false
phpunit:
    # phpunit.xml
    config: qa/phpunit.xml
    reports:
        file:
            #log: [tap]
            testdox: [html]
            #coverage: [html, clover, crap4j, php, text, xml] # requires XDebug extension

# paths are relative to .phpqa.yml, so don't copy-paste this section if you don't have custom templates

